server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.47.114.25
    username: root
    password: puzzlepop
    hikari:
      max-lifetime: 177000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: create
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 390838656947-sl2ghhogqlj04r6tgubt0v99d44flc1a.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://i10a304.p.ssafy.io/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

  servlet:
    multipart:
      max-file-size: 50MB

  data:
    redis:
      port: 6379
      host: 34.47.114.25

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.data.redis: debug  # Redis 관련 디버그 로그 활성화
    org.springframework.data.redis.core.RedisConnectionUtils: info

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  access-token-validity-in-seconds: 8640000
  refresh-token-validity-in-seconds: 144000000

OPENVIDU_URL: https://i10a304.p.ssafy.io:4443/
OPENVIDU_SECRET: MY_SECRET

FRONTEND_URL: http://34.47.114.25/

management:
  endpoints:
    web:
      exposure:
        include: prometheus

  endpoint:
    prometheus:
      enabled: true



